name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0.2
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.SCRIBD_GITHUB_RELEASE_TOKEN }}
