name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.4.4
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/exec@5.0.0
            @semantic-release/git@9.0.0
            @semantic-release/github@7.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.SCRIBD_GITHUB_RELEASE_TOKEN }}
